spring.application.name=it355pz
spring.datasource.url=jdbc:h2:mem:automatikomdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=password
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=update
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console
spring.jpa.open-in-view=true
logging.level.org.springframework.security=trace

# Weather API configuration
weather.api.url=https://api.openweathermap.org/data/2.5/weather
weather.api.key=8cabb7b8d3e327494b9c1cc17ab7c780
